using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Text;

namespace KantorLr1.ViewModels
{
	public static class ViewModelRegistrator
	{
		public static IServiceCollection RegisterViewModels(this IServiceCollection services)
		{
			services.AddSingleton<MainWindowViewModel>();
			services.AddSingleton<IterativeMethodsViewModel>();
			services.AddTransient<AutoGenerateDataViewModel>();
			services.AddSingleton<PartialEigenvalueProblemViewModel>();
			services.AddSingleton<FullEigenvalueProblemViewModel>();
			return services;
		}
	}
}
