using KantorLr1.Infrastructure.Commands.Base;
using System;
using System.Collections.Generic;
using System.Text;
using System.Windows;
using KantorLr1.View.Windows;

namespace KantorLr1.Infrastructure.Commands
{
	public class CallAutogenerateDataWindowCommand : Command
	{
		private Window window;
		public override bool CanExecute(object parameter) => window == null;

		public override void Execute(object parameter)
		{
			window = new AutoGenerateData
			{
				Owner = Application.Current.MainWindow
			};
			window.Closed += OnWindowClosed;
			window.ShowDialog();
		}

		private void OnWindowClosed(object sender, EventArgs e)
		{
			((Window)sender).Closed -= OnWindowClosed;
			window = null;
		}
	}
}
