using System;
using System.Collections.Generic;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace KantorLr1.View.Windows
{
	/// <summary>
	/// Логика взаимодействия для AutoGenerateData.xaml
	/// </summary>
	public partial class AutoGenerateData
	{
		public AutoGenerateData()
		{
			InitializeComponent();
		}
	}
}
